### ISSUE TITLE
App crashes when refreshing rates without an internet connection 

### ISSUE THREAD

**Issue by rubenvanerk** [sal0max/currencies#14]
When refreshing the rates without an internet connection, the app crashes.
I found that this was a problem while traveling without an internet connection. The app wanted to refresh the rates automatically on opening the app so it crashed immediately.
I don't really mind outdated rates but I guess for others it would be useful to show an alert that the rates are outdated.

Thanks for the app, love the simplicity!

**Comment by sal0max** [comment]
Thanks for your bug report.

Normally, the app checks if no data connection is available and shows an error message. The old cashed values can still be used, however.

What exactly happened? Did the app just disappear?

What exactly was your connection status? Were you on airplane mode? Were you connected to a network but without data connection? Was there simply no reception?

**Comment by sal0max** [comment]
I could recreate the issue this evening.
The problem only appears when the dark theme is used and seems to be caused by a bug in the Snackbar implementation in the Material library.

I implemented a fix in d29795d6eb981a2252bc157b9f7aef37e322631e
Update in the app stores should appear soon.

Thanks again, for reporting this issue.
