### ISSUE TITLE
Implement Material you

### ISSUE THREAD

**Issue by dhishkyaon** [sal0max/currencies#23]

**Comment by sal0max** [comment]
Info about Material 3/Material You: https://m3.material.io/

Any specific changes, you have in mind?

**Comment by MKCOOL142** [comment]
Yes I think you should add material you, I can make a concept of how it could look tomorrow

**Comment by sal0max** [comment]
Looking forward to, @MKCOOL142  👍

**Comment by MKCOOL142** [comment]
![Desktop - 3](https://user-images.githubusercontent.com/40364718/152014840-47b3866e-d5d0-4ff6-a830-08c06efc7f5d.png)
![Desktop - 4](https://user-images.githubusercontent.com/40364718/152014843-83afad80-8382-4019-9f1f-fb3a7a883fbd.png)
![Desktop - 1](https://user-images.githubusercontent.com/40364718/152014846-61d48e3a-51da-4d7f-8961-58d2e70e9cab.png)
I... tried but eh (also I got tiredd of copying the settings sooo only made 2 settings

**Comment by dhishkyaon** [comment]
@MKCOOL142 looks great btw

**Comment by sal0max** [comment]
Thanks for the mocks, @MKCOOL142 !

As @dhishkyaon noted, you indeed did change the layout quite a bit.
Couple of questions I got there:

- Timeline Activity
  - What does the 380zł / 82.99€ mean? Forex historic rates are always `1<baseRate> to x<targetRate>`. It doesn't make a lot of sense to compare different amounts, as the relative change will be always the same. In other words: The cart would look the same, no matter if `380zł to €` or `1zł to €`. How would the layout look, if those two unneeded values would be removed again?
  - The min, max and average values are gone. I don't want to remove functionality just because of a fancy new design. They have to fit somewhere
- Main Activity
  - Most important question: I don't really get the idea behind the new display. "Enter Price": all right! That's probably the place where the user input appears. But where does the result appear? Currently, each of those two values is next to its related currency. How should this be in your concept? Would love to see a more detailed mock to show your idea.
  - Any reason why the operathors have a different color?  In my optionion, this breaks consistency, as all are of equal meaning and equal importance.
  - You've changed the [Text buttons](https://m3.material.io/components/buttons/guidelines#c9bcbc0b-ee05-45ad-8e80-e814ae919fbb) (1, 2, 3, ...) to [Filled tonal buttons](https://m3.material.io/components/buttons/guidelines#07a1577b-aaf5-4824-a698-03526421058b). Definitely something one could do. Based on the description in the M3 guidelines I'd say that either is fine, as all buttons in that screen are of equal importance. [Samsung](https://play.google.com/store/apps/details?id=com.sec.android.app.popupcalculator) and [Google](https://play.google.com/store/apps/details?id=com.google.android.calculator) calculator use tonal buttons, and the user response, according to the reviews, is mixed. I also have mixed feelings about it. But I likely give it a shot.
  - (side note: the calculator is missing the plus sign ;) )

What I take away - in general - about M3, is the increased usage of rounded corners. So that's something I keep in mind when changing the design comes to time.
However, until then, I'd need more discussion evolve around my questions.

Maybe @dhishkyaon has some more input?. What was it exactly, that you think is definitely **not** M3 compatible about the current layout, that lead you to opening this issue?

**Comment by MKCOOL142** [comment]
@sal0max okay so to clear things up, the "enter price" is where you first input the value and then when you press enter (or while typing) it'd open the screen with the 380 zł to euro.

Ofc you can leave the min and max values I just did this late at night and wanted to sleep and safe some time 😅

No there's no reason for the operators different colors, I just copied the Google calculator but afterwards have to agree the different colors aren't needed especially since an equal button isn't needed and there's supposed to be a plus button at that spot and since the operators don't have different importances they should be all the same color

I personally think the tonal buttons work good, ofc that's personal preference but I think it looks good



Yes you're right about the increase in roundness, I'd personally also implement the android 12 wallpaper color engine thing (or this recreation which is compatible down to android 5 https://github.com/KieronQuinn/MonetCompat )

Also if you implement md3 design components it'd be good to also include the updated dialog windows with more roundness

**Comment by sal0max** [comment]
Thanks for the clarification, @MKCOOL142 ! Now I get it:

In your concept, you enter the base value and hit the/a `=` button, which brings you to the second screen, where the result + the timeline is shown.

_To be honest:_ Isn't this much more complicate than it is now? Now you can just type ahed and immediately see the result.
Timeline data is probably not to any use for most of the users for the majority of time.
In your concept, it's a steady back and forth. Doesn't really seem practical.

The question regarding min/max/avg still is a bit unsolved, as in the current concept there's simply no space for it. But that's not so important right now.


I'll have a look at the official M3 theme documentation, to maybe implement the theme engine, and of course M3 components like dialogs..
But right now, I don't see the need for big changes in the app usability.


Thanks a lot for your work and participaiton, anyway.


Let's wait what the original author @dhishkyaon has to add. :)

**Comment by dhishkyaon** [comment]
I don't have any particular demands. You guys can do whatever you like. I just like material you thats why i created the issue.

**Comment by sal0max** [comment]
Well, I just thought as you opened this issue, you had some particular stuff in mind. I don't see any breaking issues where the app violates Material 3. In my opinion, it more or less already is Material 3, if you don't count in the dynamic color stuff.

That's why I'll close this, until further crucial input will be made.

**Comment by sal0max** [comment]
Material 3 was implemented with commit 1650c28a6768748e6c6fe97e7fc1b284e5da2e8d and released in [1.14.0](https://github.com/sal0max/currencies/releases/tag/1.14.0).
