### ISSUE TITLE
Material You

### ISSUE THREAD

**Issue by xIUPITERx** [sal0max/currencies#32]
I would like to have an material design theme in the app.

**Comment by sal0max** [comment]
Tell me what about the app isn't Material 3 ("You"), first.

**Comment by xIUPITERx** [comment]
The design is very appealing, but the colors are part of the material you theme.

![Screenshot_20220915_001838.jpg](https://user-images.githubusercontent.com/97352673/190273002-65d20959-adc2-46ad-b330-ce0ed491338f.jpg)

You can see that the color theme of the currencies app doesn't fully match the color of the Google drive app.
E.g. why are there green colored buttons?

**Comment by xIUPITERx** [comment]
Please don't get me wrong, I like the design very much, but there are still these little inconsistencies that don't fit in 100%.

**Comment by sal0max** [comment]
Okay, thanks a lot for the clarification.

There are so many aspects to Material 3, and so many possibilities. Hence it's hard to understand what one means with such a generic request like "_I would like to have an material design theme in the app_". Especially when there [was already a discussion](https://github.com/sal0max/currencies/issues/23) and I have already implemented the [Material 3 base theme](https://github.com/sal0max/currencies/issues/23#issuecomment-1137810133).

So, I take you propose to change the fixed primary color to a dynamic color on devices with API ≥ 31.
This would make everything that's green right now dynamic: arithmetic buttons, floating action buttons, settings headings, etc.
That's definitely something I would consider.

This would be the result:

![dynamic-primary](https://user-images.githubusercontent.com/423373/192118191-c32b9c85-7e33-47db-af93-cda353c5bdea.png)

Also, while at it, I could add support for a monochrome launcher icon:

![monochrome-launcher-icon](https://user-images.githubusercontent.com/423373/192118732-05b47a1c-9990-470f-8790-c059490b05ec.png)

Is that what you had in mind?

**Comment by xIUPITERx** [comment]
That looks wonderful
And maybe have an option to match the colour of the delete button.

**Comment by xIUPITERx** [comment]
I have another question, is the background colour behind the green button part of Material 3?
I have hardly seen it in any other app.
Normally, such surfaces tend to have darker colours.

**Comment by sal0max** [comment]
Light mode: https://github.com/sal0max/currencies/blob/master/app/src/main/res/values-v31/colors.xml#L5
Dark mode: https://github.com/sal0max/currencies/blob/master/app/src/main/res/values-night-v31/colors.xml#L5

So, it's lighter than the background in dark mode and darker than the background in light mode.
Also, it's dynamic.

**Comment by xIUPITERx** [comment]
Light mode comparison:
![Screenshot_20220925-003134_Currencies.jpg](https://user-images.githubusercontent.com/97352673/192120997-3c7d9a12-c94d-4cb4-9278-c6b47588ac2e.jpg)

Dark mode Comparison:
![Screenshot_20220925-003144_Currencies.jpg](https://user-images.githubusercontent.com/97352673/192121005-d61b009e-a8d1-4429-8c61-a38127d72ae9.jpg)

Could that also be changed? So that it looks like the GApps.

**Comment by xIUPITERx** [comment]
If not everybody wants it, you could add an option like the oled black one.

**Comment by sal0max** [comment]
Alright, thanks for the additional feedback.

My two cents:
- Not every app should be a clone of one "benchmark" app, if there exists even such a thing. Especially because the GApps themselves often disobey design guidelines (take e.g. Maps).
  Also, check out the [Google Calculator app with M3 design](https://play.google.com/store/apps/details?id=com.google.android.calculator). There, the display is brighter than the number pad in dark mode and darker in light mode. Additionally, buttons are not all the same color tone, but have different shades, depending on function and importance.
- It is definitely not the right way, to clutter an app in making an option for every little detail, especially when it is _only_ the look. Might be something an enthusiast wishes, but that is absolutely counterproductive for the average user.

I will try out different kinds of background shades and how a dynamically colored delete button will look, but there will be no options for it.

**Comment by xIUPITERx** [comment]
Perfect, I don't want all apps to look exactly the same, but I think the GApps Material You has been implemented very well. It would definitely be nice if the colour theme also applied in surfaces.

**Comment by sal0max** [comment]
As written: The surface colors already are dynamic. [Check out the docs](https://developer.android.com/reference/android/R.color#system_neutral1_0). There is a ton of different dynamic colors. The apps from your screenshots just chose to pick more flashy tones.

There are plenty of people which don't like that apps all look completely tinted with some striking color. I'm one of them. It makes them less distinguishable. Just read the reviews of the [Google Calculator app](https://play.google.com/store/apps/details?id=com.google.android.calculator). That's why I don't want to go full _paint bucket mode_.

I like constructive feedback. But to be honest, it's a bit annoying you just wanting me to 100% imitate other apps when you seemingly didn't even understand that Material 3 isn't "_do it exactly this way and no way else_". This isn't Holo any more.

**Comment by xIUPITERx** [comment]
I just wanted to avoid any misunderstandings as English is not my mother tongue.

**Comment by sal0max** [comment]
Dynamic colored buttons added in 920962b02583dd88edba6560e0f4640b88341f4b.
As already stated: Background colors already are fully dynamic.

Will arrive with the next update in the app stores.
