### ISSUE TITLE
Feature : An Extra user configurable currency 

### ISSUE THREAD

**Issue by S-360** [sal0max/currencies#4]
Add an EXTRA currency which is linked to the Dollar or Euro that the user can set a custom exchange rate for.

 If the desired currency isn't available you can simple use the EXTRA currency.

**Comment by sal0max** [comment]
I know of some currencies linked to the USD. Mostly middle eastern money.
Like the Bahraini dinar (_1 USD = 0,376 BHD_), the Saudi riyal (_1 USD = 3,75 SAR_), United Arab Emirates dirham (_1 USD = 3.6725 AED_) and so on…

Are those the use case for your proposed feature?
Because maybe it's better to just hard code those into the app. Could indeed be useful.
_UAE seems a popular vacation location, in these times…_

If not, what is your use case?

**Comment by S-360** [comment]
Not exactly....guess I'm not that great at explaining what I mean, I'll try again.

There is actually another currency app on Fdroid which has this feature.

They have created and extra currency called EXT which by default is 1=1 to the Euro. There is a menu option for the user to change/set this rate.

For exaple the user can Set EXT=2.45 now 1EUR=2.45EXT

You can then pair the EXT currency with any other, works really well.

This would save you from having to add ever single currency to the app. The user could simply use the EXT currency and set a rate to whatever they want against the euro.
(Not sure why the other app chose euro as default seeing as the USD is the world reserve currency) 

Additionally maybe allow the user to create Multiple EXT currencies and also allow custom names?

So for example users could set/change 
EXT1 = UAE
EXT2 = PKR
EXT3 = BTC
and so on


Also perhaps the ability to show more than one currency to the user at a time?

I prefer your app, UI is much nicer and the calculator feature is great!

Here is a link, perhaps you could check it out.

https://f-droid.org/repo/org.billthefarmer.currency

https://github.com/billthefarmer/currency

**Comment by sal0max** [comment]
Okay, I get your idea: Add additional currencies, with a custom rate relative to another selectable currency.

Still, if you don't count small countries like Kiribati and if you neglect currencies with a rate of 1:1, there are only a handful of currencies which are linked to EUR/USD/…:
https://en.wikipedia.org/wiki/List_of_circulating_fixed_exchange_rate_currencies

Wouldn't it be much user friendlier to hard code those few? I'm thinking of e.g. AED, BHD, QAR, SAR, and maybe some others.
I'd imagine a typical user, going on vacation in Dubai, rather wants to just select the dirham instead of informing himself about the exchange rate and having to program it.

Regarding your example with PKR and BTC:
In my opinion it doesn't really make sense, as those two currencies aren't pegged to another currency, so you'd have to constantly keeping them updated.

**Comment by S-360** [comment]
Interesting, thanks for that link. Guess it would be easier to hard code seeing as those currencies are pegged to USD

Still, would be nice option to have that extra currency for those that would like to customise.

**Comment by sal0max** [comment]
I've thought about it and came to following conclusion:

- My app is aimed for recreational use like on vacations. It is important that it covers the currencies of the major touristic countries. A lot of those countries use currencies pegged to USD or EUR. With 56e8cdcb1d81e655b150e2df32d67fafe4b0345e I am now supporting a whole bunch of them.
This issue helped a lot to let me realize this need and also the possibility to include those currencies, without having to switch to a commercial API. Thanks for that!

- However, regarding the original suggestion, the inclusion of customizable currencies: For now I want to deny that request. 
Again: This is an app for the average holidaymaker. I think it is too big a danger, that one includes his "own" currency, isn't aware or forgets to update it and blames the app for displaying wrong data.
I can't really think of a use case that is in the scope of this app.
