### ISSUE TITLE
Hardware keyboard not supported

### ISSUE THREAD

**Issue by lord-aerion** [sal0max/currencies#54]
I have two devices with hardware keyboards, the _Gemini_ and _Cosmo Communicator_ by Planet Computers.

While the app supports the default landscape mode of these devices beautifully, I cannot enter data using the hardware keyboard, i.e., I have to use the on-screen numberpad.

**Comment by sal0max** [comment]
Those two devices look fun. Wasn't aware of something like that since the Motorola Milestone/Droid.

I added the requested hardware keyboard support. The current Play Store release already includes the feature.

As I'm lacking real test devices, I'd appreciate feedback, if everything is working fine.

**Comment by lord-aerion** [comment]
Yeah, they're pretty cool devices. There's a third one, called the Astro Slider. They have their limitations though, the biggest one being just 2 years of Android updates. My Cosmo, for example, is now forever stuck on Android 9. They can run Linux proper though, as well as Sailfish and Ubuntu Touch, so they've got some longer life that way.

Anyway, I've just installed the latest apk from Github via Obtainium (I was using the F-Droid build), and the keyboard now works perfectly!

Thank you so much for implementing this so quickly!

I'll send you a donation later today or tomorrow.
