### ISSUE TITLE
[Feature Request] add crypto currencies (https://api.exchangerate.host/cryptocurrencies)

### ISSUE THREAD

**Issue by iNtEgraIR2021** [sal0max/currencies#8]
Hi 👋🏼 

great app. Looks amazing 👍🏼 I love the design. 

Any chance to add the **cryptocurrencies** provided by [**exchangerate.host**](https://api.exchangerate.host/cryptocurrencies)?

Would love to see that implemented. Hope you have the time for that. Big thank you in advance. 🙏🏼 

I'm very grateful for the time and effort you invest in this project. 

Greetings, Petra

**Comment by sal0max** [comment]
Thanks for your kind words.

I was and still am always a bit wary with crypto currencies in this app for those reasons:
1. Like written in the app introduction (_"It is not intended to be used for realtime financial business, rather to be a handy companion e.g. on vacations."_), cryptocurrencies would be out of the scope of this project. You normally don't need cryptocurrencies in the real world, paying your cheeseburger.
Because of the scope of this project, the auto-refreshing of the currency rates just happens only once a day. For heavily fluctuating crypto currencies, this refresh rate can lead to serious miscalulations, which I don't want to be responsibly for.
2. If you're using crypto currencies, you most likely already use some kind of wallet app. Those apps all provide as reliable currency rates, as it can get. I see crypto currencies as a special niche, hardly comparable with established forex trade. And as that, in my opinion, you're better off with an app specialising on that niche.
3. There's currently an open issue on exchangerate.host, stating that BTC exchange rates are heavily off, which only confirms my wariness on this topic:
https://github.com/Formicka/exchangerate.host/issues/64

However, even if chances are low on implementing that feature, I'm still open for discussion. What would be your use-case?

**Comment by iNtEgraIR2021** [comment]
Thank you for your answer and providing valuable background information on this.
I'll close this issue as I see based on limitations named no added value to the project at this time.
Having only daily updates of the data renders it for highly fluctuating currencies rather useless.
Might change if the api providers change their update rates.

I guess adding more translations as suggested in #11 might be have a much bigger positive impact in terms of usability.
